fts-mon:
    image: docker.cern.ch/fts/fts-mon:dev-26042016
    volumes:
     - /etc/fts3:/etc/fts3
     - /var/log/fts3:/var/log/fts3
    environment:
     - "constraint:node==ft-xe65ot56gni-1-b2nvlgobelzf-swarm-node-2vaxrrydedbw.novalocal"
    entrypoint: sleep 1000000000000000000000000000
    ports:
     - "8449:8449"
    domainname: cern.ch
    hostname: ft-xe65ot56gni-1-b2nvlgobelzf-swarm-node-2vaxrrydedbw
