fts-server:
    image: docker.cern.ch/fts/fts-server:dev-21042016
    volumes:
     - /etc/fts3:/etc/fts3
     - /var/log/fts3:/var/log/fts3
    environment:
     - "constraint:node==ft-xe65ot56gni-1-b2nvlgobelzf-swarm-node-2vaxrrydedbw.novalocal"
    ports:
     - "8446:8446"
